### ISSUE TITLE
stbridge.so STLink_GetNbDevices20TEnumStlinkInterface undefined symbol issue

### ISSUE THREAD

**Issue by amigomcu** [dragonlock2/stbridge#1]
hi ,
i try to build and it should be success. but when import "stbridge.so" it error (not found  symbol)
it seem py2.7 /python3 issue ? how ot solve?
 
parallels@parallels-Parallels-Virtual-Platform:~/Downloads/test_stpy$ env PYTHONPATH='/home/parallels/Downloads/test_stpy/lib' python
Python 2.7.17 (default, Sep 30 2020, 13:38:04) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys,os
>>> sys.path.append(os.getcwd())
>>> import stbridge as st
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/parallels/Downloads/test_stpy/lib/stbridge.so: undefined symbol: _Z19STLink_GetNbDevices20TEnumStlinkInterface

boost_python(it is py27)
------------
>>> util.find_library("boost_python")
'libboost_python-py27.so.1.65.1'
------------

setup.py
-------
ext = Extension(
    'stbridge',
    sources=['stbridge.cpp', 'bridge/bridge.cpp', 'common/criticalsectionlock.cpp',
    	'common/stlink_device.cpp', 'common/stlink_interface.cpp', 'error/ErrLog.cpp'],
    libraries=['boost_python-py27'],
    extra_compile_args=['-std=c++17', '-Ibridge', '-Icommon', '-Ilibs/src/error'],
    extra_link_args=['-L.', '-lusb-1.0', '-lfmt','-Llib/libSTLinkUSBDriver.so']
)
------

build log(it show python3??)
------------
python3 setup.py build_ext --inplace
running build_ext
building 'stbridge' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/bridge
creating build/temp.linux-x86_64-3.6/common
creating build/temp.linux-x86_64-3.6/error
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c stbridge.cpp -o build/temp.linux-x86_64-3.6/stbridge.o -std=c++17 -Ibridge -Icommon -Ilibs/src/error
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c bridge/bridge.cpp -o build/temp.linux-x86_64-3.6/bridge/bridge.o -std=c++17 -Ibridge -Icommon -Ilibs/src/error
bridge/bridge.cpp: In member function ‘Brg_StatusT Brg::CalculateI2cTimingReg(I2cModeT, int, double, int, int, int, bool, uint32_t*)’:
bridge/bridge.cpp:969:12: warning: variable ‘targetPeriodI2C’ set but not used [-Wunused-but-set-variable]
     double targetPeriodI2C; // Target period of clock
            ^~~~~~~~~~~~~~~
bridge/bridge.cpp:1105:6: warning: variable ‘l’ set but not used [-Wunused-but-set-variable]
  int l = 0;
      ^
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c common/criticalsectionlock.cpp -o build/temp.linux-x86_64-3.6/common/criticalsectionlock.o -std=c++17 -Ibridge -Icommon -Ilibs/src/error
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c common/stlink_device.cpp -o build/temp.linux-x86_64-3.6/common/stlink_device.o -std=c++17 -Ibridge -Icommon -Ilibs/src/error
In file included from common/stlink_device.cpp:25:0:
common/stlink_device.h: In constructor ‘StlinkDevice::StlinkDevice(STLinkInterface&)’:
common/stlink_device.h:109:7: warning: ‘StlinkDevice::m_bOpenExclusive’ will be initialized after [-Wreorder]
  bool m_bOpenExclusive;
       ^~~~~~~~~~~~~~~~
common/stlink_device.h:106:20: warning:   ‘STLinkInterface* StlinkDevice::m_pStlinkInterface’ [-Wreorder]
  STLinkInterface * m_pStlinkInterface;
                    ^~~~~~~~~~~~~~~~~~
common/stlink_device.cpp:42:1: warning:   when initialized here [-Wreorder]
 StlinkDevice::StlinkDevice(STLinkInterface &StlinkIf): m_bStlinkConnected(false),m_bOpenExclusive(false),
 ^~~~~~~~~~~~
common/stlink_device.cpp: In member function ‘STLinkIf_StatusT StlinkDevice::PrivOpenStlink(const char*, bool)’:
common/stlink_device.cpp:164:9: warning: unused variable ‘pEnumUniqueId’ [-Wunused-variable]
  char * pEnumUniqueId = devInfo2.EnumUniqueId;
         ^~~~~~~~~~~~~
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c common/stlink_interface.cpp -o build/temp.linux-x86_64-3.6/common/stlink_interface.o -std=c++17 -Ibridge -Icommon -Ilibs/src/error
common/stlink_interface.cpp: In member function ‘STLinkIf_StatusT STLinkInterface::EnumDevicesIfRequired(uint32_t*, bool, bool)’:
common/stlink_interface.cpp:319:11: warning: unused variable ‘status’ [-Wunused-variable]
  uint32_t status = SS_OK;
           ^~~~~~
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c error/ErrLog.cpp -o build/temp.linux-x86_64-3.6/error/ErrLog.o -std=c++17 -Ibridge -Icommon -Ilibs/src/error
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/stbridge.o build/temp.linux-x86_64-3.6/bridge/bridge.o build/temp.linux-x86_64-3.6/common/criticalsectionlock.o build/temp.linux-x86_64-3.6/common/stlink_device.o build/temp.linux-x86_64-3.6/common/stlink_interface.o build/temp.linux-x86_64-3.6/error/ErrLog.o -lboost_python-py27 -o /home/parallels/Downloads/test_stpy/stbridge.cpython-36m-x86_64-linux-gnu.so -L. -lusb-1.0 -lfmt -Llib/libSTLinkUSBDriver.so
--------------------------------------

**Comment by dragonlock2** [comment]
Change `python3` in the `Makefile` to just `python` or `python2`. Looks like `setup.py` builds an extension for the Python version that ran it.

**Comment by amigomcu** [comment]
hi ,
thank you for your reply.
it have same issue with libSTLinkUSBDriver.so (*2)

Could be attach libSTLinkUSBDriver.so (i get from *1, .)
i have been build at python2 . 

it have same issue "STLink_GetNbDevices20TEnumStlinkInterface" symbol.

*1
https://github.com/RichStrong/STLINK-V3SET-I2C-TEST.git

$ nm ./libSTLinkUSBDriver.so 
nm: ./libSTLinkUSBDriver.so: no symbols(it is dymaic lib)

Python 2.7.17 (default, Sep 30 2020, 13:38:04) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import libSTLinkUSBDriver,stbridge
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define init function (initlibSTLinkUSBDriver)


*2.
ibSTLinkUSBDriver.so 

i don't build it .so i get it from *1
-------
libs/src/common/stlink_interface.cpp:349:27: error: ‘LIBUSB_OPTION_LOG_LEVEL’ was not declared in this scope
    libusb_set_option(ctx, LIBUSB_OPTION_LOG_LEVEL, LIBUSB_LOG_LEVEL_INFO);
                           ^~~~~~~~~~~~~~~~~~~~~~~
libs/src/common/stlink_interface.cpp:349:27: note: suggested alternative: ‘LIBUSB_ERROR_NO_MEM’
    libusb_set_option(ctx, LIBUSB_OPTION_LOG_LEVEL, LIBUSB_LOG_LEVEL_INFO);
                           ^~~~~~~~~~~~~~~~~~~~~~~
                           LIBUSB_ERROR_NO_MEM
libs/src/common/stlink_interface.cpp:349:4: error: ‘libusb_set_option’ was not declared in this scope
    libusb_set_option(ctx, LIBUSB_OPTION_LOG_LEVEL, LIBUSB_LOG_LEVEL_INFO);
    ^~~~~~~~~~~~~~~~~
libs/src/common/stlink_interface.cpp:349:4: note: suggested alternative: ‘libusb_get_version’
    libusb_set_option(ctx, LIBUSB_OPTION_LOG_LEVEL, LIBUSB_LOG_LEVEL_INFO);
    ^~~~~~~~~~~~~~~~~
    libusb_get_version
error: command 'gcc' failed with exit status 1

-------

platform:
$ uname -ra
Linux parallels-Parallels-Virtual-Platform 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dragonlock2** [comment]
libSTLinkUSBDriver.so is unnecessary with this code so you can remove the linker option and import for it. Not sure why you have a `libusb_set_option` compile error because it looks like it compiled fine before but if it's still causing issues you can just comment that line out.

**Comment by amigomcu** [comment]
hi  dragonlock2 ,
thank your help.

i get it , 
i checkout lib STLINK-V3-BRIDGE .
* (HEAD detached at 92ba6c8)

parallels@parallels-Parallels-Virtual-Platform:~/Downloads/stbridge$ sudo python all.py 
[sudo] password for parallels: 
Connected! Starting tests...

Testing GPIO...
('Flashing GPIO', 0, '\x08...')
('Flashing GPIO', 1, '\x08...')
('Flashing GPIO', 2, '\x08...')
('Flashing GPIO', 3, '\x08...')
Reading GPIO using internal pull-ups, so disconnect any loads
('Reading GPIO', 0, '\x08...', 'SUCCESS')
('Reading GPIO', 1, '\x08...', 'SUCCESS')
('Reading GPIO', 2, '\x08...', 'SUCCESS')
('Reading GPIO', 3, '\x08...', 'SUCCESS')
('Reading GPIO', 0, '\x08...', 'SUCCESS')
('Reading GPIO', 1, '\x08...', 'SUCCESS')
('Reading GPIO', 2, '\x08...', 'SUCCESS')
('Reading GPIO', 3, '\x08...', 'SUCCESS')

Done!
