### ISSUE TITLE
BRG_ERROR: 1 BRG_CONNECT_ERR,          ///< USB Connection error

### ISSUE THREAD

**Issue by muhammetkocak0** [dragonlock2/stbridge#9]
prodigytrip@prodigytrip-IdeaPad-Gaming-3-15ARH05:~/stbridge$ python3 tests/all.py
Traceback (most recent call last):
  File "/home/prodigytrip/stbridge/tests/all.py", line 5, in <module>
    dev = st.USBInterface.list_devices()[0]
RuntimeError: BRG_ERROR: 1

**Comment by dragonlock2** [comment]
Tracked down to an issue with exclusive opening, works on macOS and Linux now. Exposed another issue on the Windows side, working on it

**Comment by muhammetkocak0** [comment]
I work on Linux already.
